name: Split and Release Images
on:

  workflow_dispatch: {}



permissions:

  contents: write



jobs:

  split-and-release:

    runs-on: ubuntu-latest



    steps:

      - name: Pull Docker Images

        run: |

          docker pull docker.elastic.co/elasticsearch/elasticsearch:8.11.4



      - name: Compress and Split Images

        run: |

          mkdir dist

          docker save docker.elastic.co/elasticsearch/elasticsearch:8.11.4 \

            | gzip | split -b 200m - dist/om-es.tar.gz.



      - name: Create GitHub Release

        uses: softprops/action-gh-release@v2



        with:

          tag_name: v1.13.1

          name: "OpenMetadata 1.13.1 Docker Images"

          draft: false

          prerelease: false

          files: dist/*



        env:

          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
